Add lesson_4_js_basics.js file with homework
HKhrystyna/automation_project pull request #2
Opened 2023-10-29 23:27 UTC by HKhrystyna

In this PR you can find lesson_4_js_basics.js file with my first working functions.
Thanks in advance for your review and feedback!

2023-10-30 20:07 UTC, Art-auto commented on lesson_4_js_basics.js
> +/* FYI @Artem, cудячи з назви функції та прикладу роботи умова повинна виглядати так:
так, вже коли почав перевіряти домашки помітив, що в умові трохи наплутано. Хтось робив по умові, хтось по назві функції - я все зараховував

2023-10-30 20:09 UTC, Art-auto requested changes
please install the cypress (it is missing in the package.json)

2023-11-01 20:21 UTC, HKhrystyna commented
@Art-auto cypress is installed now, please review PR again

2023-11-02 19:44 UTC, Art-auto approved these changes
Thanks, now all good

2023-11-06 18:56 UTC, merged